package com.chenyuhui.mybatis.mapper;

import com.chenyuhui.mybatis.pojo.Employee;
import com.chenyuhui.mybatis.pojo.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    Employee selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cyh_employee
     *
     * @mbggenerated Fri Jul 29 09:09:09 CST 2022
     */
    int updateByPrimaryKey(Employee record);
}